In [37]:

import numpy as np
import pyvrp as vrp
import pandas as pd

In [38]:
data_nodos=pd.read_excel(r'Datos/data.xlsx', sheet_name=0)

data_vehiculos=pd.read_excel(r'Datos/data.xlsx', sheet_name=1)

data_nodos.head()

    Nodos  Coor_X  Coor_Y  Demanda  Tiemp_Serv  Horario_aper  Horario_cierre
0  Nodo_0      15      84        0         NaN           NaN             NaN
1  Nodo_1      20      65        5         NaN           NaN             NaN
2  Nodo_2      25      32        8         NaN           NaN             NaN
3  Nodo_3      15      38        9         NaN           NaN             NaN
4  Nodo_4      98       4        4         NaN           NaN             NaN

In [39]:
data_vehiculos.head()

         Tipo  Cantidad  Capacidad
0  Vehiculo_0         5          8
1  Vehiculo_1         2         20
2  Vehiculo_2         3         15
3  Vehiculo_3         2         12

In [40]:
data_nodos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Nodos           24 non-null     object
 1   Coor_X          24 non-null     int64
 2   Coor_Y          24 non-null     int64
 3   Demanda         24 non-null     int64
 4   Tiemp_Serv      0 non-null      float64
 5   Horario_aper    0 non-null      float64
 6   Horario_cierre  0 non-null      float64
dtypes: float64(3), int64(3), object(1)
memory usage: 1.4+ KB

In [41]:
m=vrp.Model()

m.add_depot(x=data_nodos.iloc[0,1],y=data_nodos.iloc[0,2])

In [42]:
for i in range(1,24):
    m.add_client(x=data_nodos.iloc[i,1],y=data_nodos.iloc[i,2])

In [43]:
data_vehiculos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Tipo       4 non-null      object
 1   Cantidad   4 non-null      int64
 2   Capacidad  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [76]:
for j in range(0,4):
    m.add_vehicle_type(num_available=data_vehiculos.iloc[j,1], capacity=[data_vehiculos.iloc[j,2] for k in range(0,data_vehiculos.iloc[j,1])], start_depot=m.locations[0], end_depot=m.locations[0], reload_depots=[m.locations[0]])

In [77]:
for frm_idx, frm in enumerate(m.locations):
    for to_idx, to in enumerate(m.locations):
        m.add_edge(frm, to, distance=abs(frm.x - to.x) + abs(frm.y - to.y))

In [79]:


from pyvrp.stop import MaxRuntime

res = m.solve(stop=MaxRuntime(2), display=True)

ValueError: Vehicle type has inconsistent capacity size.